### ISSUE TITLE
exclude-pseudoclasses undesirable effects with :first-child usage

### ISSUE THREAD

**Issue by evenicoulddoit** [peterbe/premailer#177]
Hey,

I believe the `exclude-pseudoclasses` argument is responsible for leaving CSS rules within the `<style>` attribute, but this can create undesirable consequences.

If I try to use the pseudoclass `:first-child`, I get mixed results. Using a selector without a child rule works fine. Take the given DOM structure:

```html
<table class="foo">
  <tr class="bar">
    <td class="zulu"></tr>
  </tr>
</table>
```

The below transforms the `.bar` element as expected:

```css
.bar:first-child {
  background-color: red;
}
```

But applying a child rule of `.zulu` does not work, and leaves the rule in the head:

```css
.bar:first-child .zulu {
  background-color: blue;
}
```

Is there a reason for this? It seems that if you are able to reason about the `:first-child`, you should also be able to reason about the second situation?

Thanks, happy to provide a test case is this behaviour is undesired.

(Also, I was looking through the tests, `::first-letter` is a pseudo-*element*, not a pseudo-class)
