### ISSUE TITLE
Nested selector with :not not working correctly

### ISSUE THREAD

**Issue by nuschk** [peterbe/premailer#179]
I had a problem using foundation for emails using premailer, which broke rendering almost completely.

It's basically this:

```python
from premailer import transform
print(transform("""
<html>
    <style type="text/css">
        .bla .bli:not(.blu) { border:1px solid black }
    </style>
    <div class="bla">
        <div class="bli">Peter</div>
    </div>
</html>
"""))
```

Which transforms to:

```html
<html>
    <head>
        <style type="text/css">.bla .bli:not(.blu) {border:1px solid black}</style>
    </head>
    <body>
        <div class="bla">
            <div class="bli">Peter</div>
        </div>
    </body>
</html>
```

The border style should be applied to the div.bli. 

I know, it's already quite arcane and I wouldn't code my email layouts like this, but it's a pattern used in stock foundation, so I thought it might be worthwhile to investigate.

BTW, thanks so much for your work on premailer!

**Comment by peterbe** [comment]
The tricky reality is that premailer depends on `cssselect` and `lxml`. I really wish there was a well documented list of limits to its functionality. It's simply not as powerful as `document.querySelector` in DOM or the `$()` function in jQuery.

**Comment by nuschk** [comment]
Yeah, I thought that it might be buried somewhere deep. 

Let's close the issue then. For the purpose of documentation, here's the code I added to my custom SCSS in order to get foundation for emails work with premailer:

```css
td.columns table,
td.column table,
th.columns table,
th.column table {
    width: 100%;
}

td.columns table.button,
td.column table.button,
th.columns table.button,
th.column table.button {
    width: inherit;
}
```
