### ISSUE TITLE
CSS rules in media query are not minified like normal remaining css rules are

### ISSUE THREAD

**Issue by adambullmer** [peterbe/premailer#191]
It would fantastic if CSS rules inside of media queries were minified in the same way that remaining css rules left in the page were. I believe the issue is in this block: https://github.com/peterbe/premailer/blob/master/premailer/premailer.py#L629-L634 as compared to the formatting happening above: https://github.com/peterbe/premailer/blob/master/premailer/premailer.py#L623

Consider the following contrived example:
```css
.unused-class {
  font-size: 16px;
}

@media (max-width: 480px) {
  .unused-class {
    font-size: 14px;
  }
}
```

### What I expect to happen:
The output of premailer would minify the css in a consistent manner:
```css
.unused-class {font-size: 16px}
@media (max-width: 480px) {
  /* on a new line or not doesn't matter to me */
  .unused-class {font-size: 14px }
}
```

### What actually happens:
The output of css rules inside of a media query are not rewritten
```css
.unused-class {font-size: 16px}
@media (max-width: 480px) {
  .unused-class {
    font-size: 14px;
  }
}
```
